### ISSUE TITLE
Bot in MS Team chat not accurately using LUIS - appends teams bot channel to luis.

### ISSUE THREAD

**Issue by mlipinski** [microsoft/botframework-solutions#3194]
#### What project is affected?

LUIS fails to properly predict the proper intent when coming from MS Team when in a chat or a channel.

#### What language is this in?

C#

#### What happens?

The utterance sent to LUIS from the bot in MS Teams includes <at> bot channel name <at> at the beginning of every utterance which throws off LUIS prediction score.

#### What are the steps to reproduce this issue?

Add a bot into a Chat or a Channel to the point where you need to interact with it by using @botname within Teams.

#### What were you expecting to happen?

I was not expecting the utterance sent to LUIS to include the bots channel name. 

#### Can you share any logs, error output, etc.?

I am including a screen shot where the channel name is prefixed to the utterance and how that modifies the correct intent which it normally picks when not in a Team channel or Chat.  

#### Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/5796298/76791990-65de9f80-6798-11ea-84b0-02396b10f357.png)

**Comment by xieofxie** [comment]
Hi @mlipinski, please see this https://github.com/microsoft/botframework-solutions/pull/2745/files. It is not updated to docs yet

**Comment by mlipinski** [comment]
So here is my update, I added the bit of code to check for teams and I am still seeing the following in LUIS:

< at >           < /at >  what I typed in here 

So while the code does remove the sender from Teams, it doesn't also get rid of the < at >    < /at > which I believe will still alter the LUIS results.

**Comment by xieofxie** [comment]
Hi @mlipinski I have tried this and it removed < at >< /at >.

The code behind function is here https://github.com/microsoft/botbuilder-dotnet/blob/f2ea94df840195ac4d7a14ee2695814f67f7febe/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L64

Could you pause when it calls the function and view the content of turnContext.Activity.Entities?
For myself, its mention.Text is not null and it is like < at > name< /at >, so it will be removed entirely.

**Comment by lauren-mills** [comment]
@mlipinski - has your issue been resolved?

**Comment by lippy1m** [comment]
I am not seeing the utterances in LUIS show up with the <<at>> any more, so yes it has.

**Comment by peterinnesmsft** [comment]
Per @lippy1m, sounds like the issue has been resolved, so closing out. If it occurs again, feel free to reactivate the issue and we can take a further look.

**Comment by rslavey** [comment]
I'm still seeing this in group chats where someone invites the bot:

    < at > my bot < / at > people in accounting

Was this only fixed for a bot in a team and not a group chat?
