### ISSUE TITLE
[CalendarSkill] Schdule a meeting for today at 5 PM doesn't work

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#802]
**Project**
Skills

**Description**
When I say "Schedule a meeting today at 5 PM" you get a very weird response:
![image](https://user-images.githubusercontent.com/12264946/52864702-b8b6d500-3108-11e9-8bee-38e4cef453db.png)

**To Reproduce**
Say schedule a meeting for today at 5 PM

**Expected behavior**
There are many issues here:
- The response message is missing data (see screenshot) and not worded correctly
- The bot is assuming a subject of meeting
- The bot is not prompting for meeting message (not sure if it should)
- The bot is not prompting for topic (not sure if it should)
- The bot is not prompting for location (not sure if it should)

**Comment by garypretty** [comment]
@gabog I had a similar discussion recently with @lauren-mills.  It looks like the calendar skill is designed (right now) to assume default or no values for several of the meeting properties.  My gut feeling is this was done for a specific customer need and the assistant should probably be updated to always prompt for each property, with individual customers being able to customise for their needs - otherwise it feels inconsistent with the experience you get if you simply say "schedule a meeting".  

This all seems to hang off checks on the property createHasDetail, which is set to true if the skill has managed to derive any info about the meeting you want to schedule from your initial utterance.

If we can get agreement that this is a sensible thing to do then I am happy to make the change and submit a PR as I have mostly done this locally already for a customer demo last week.

**Comment by bobokids** [comment]
The behavior that using default value and avoiding too much prompt is currently by design.

**Comment by gabog** [comment]
Even if it is by design, the wording in the confirmation is wrong:
The event is **on** Today **at at** till **at** 5:30 ... the Event will take place at **?** … the message is **?** 
I would not just limit this bug to fixing the string concatenation, probably rephrase the confirmation to shorter more conversational way, "OK, I am ready to create a 30 minutes meeting for today at 5 PM, sounds good?"

**Comment by KayMKM** [comment]
fixed

**Comment by gabog** [comment]
I just recheked this on master and the phrasing for the response is still not quite right, re-opening the issue, here are some examples.

Ping me or Dewain offline if you need more details.

![image](https://user-images.githubusercontent.com/12264946/53650857-c78fa280-3c45-11e9-837e-725cd8545acc.png)


![image](https://user-images.githubusercontent.com/12264946/53650876-d2e2ce00-3c45-11e9-9577-9115d1b039b6.png)

![image](https://user-images.githubusercontent.com/12264946/53650928-eee66f80-3c45-11e9-8958-e725cbe508c9.png)

**Comment by darrenj** [comment]
@garypretty Very good observation about the skill being too skewed in a particular customers direction. At the very least we should make this behaviour configurable so it does prompt "more" for more precise understanding rather than assuming subject title. The core of the skill is general purpose customer usage.

Perhaps something along the lines of a config property, "compactDialog" on the skill that will change the behaviour to be "brief" in line with some customer scenarios (e.g. car)

@rng Would be great to get your perspective on the above, specifically the "compact" dialog where it doesn't prompt for location and other information and whether this is what you expected? I like the ability to shortcut but not at the expense of the user perhaps wanting to add more information which they aren't prompted for. We could perhaps use this "compact flow" for situations where brevity is desired but make this behaviour optional, thoughts?

**Comment by KayMKM** [comment]
fixed and merged.
